"use client";
import { useState, type FormEvent } from "react";
import { Eye, EyeOff } from "lucide-react";
import "./auth.css";
export type AuthMode = "login" | "register" | "reset";
export default function AuthPage({authenticate}: {authenticate:(mode:AuthMode,values:{email:string;password:string;name:string})=>Promise<{message?:string}>}) {
 const [mode,setMode]=useState<AuthMode>("login"),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 function change(next:AuthMode){setMode(next);setError("");setMessage("");setVisible(false);}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError("");setMessage("");try{const result=await authenticate(mode,{email:String(data.get("email")||"").trim(),password:String(data.get("password")||""),name:String(data.get("name")||"").trim()});if(result.message)setMessage(result.message);}catch(e){setError(e instanceof Error?e.message:"We couldn’t complete that request. Please try again.");}finally{setBusy(false);}}
 return <div className="auth-shell"><header className="auth-header"><a href="/portal" className="auth-brand" aria-label="Creativista Portal home"><img src="/brand/logo.jpg" alt=""/><span>Creativista<span>Portal</span></span></a><a href="/">Visit CreativistaPods</a></header><main className="auth-main"><section className="auth-form" aria-labelledby="auth-title"><h1 id="auth-title">{mode==="register"?"Your family’s next chapter.":mode==="reset"?"Reset your password.":"Welcome back."}</h1><p>{mode==="register"?"Create an account to start your family’s application.":mode==="reset"?"Enter your email and we’ll send a password reset link.":"Sign in to manage your family’s enrollment."}</p>{error&&<div className="auth-notice error" role="alert">{error}</div>}{message&&<div className="auth-notice" role="status">{message}</div>}<form onSubmit={submit} key={mode}><fieldset disabled={busy}>{mode==="register"&&<label>Full name<input name="name" autoComplete="name" required maxLength={100}/></label>}<label>Email address<input name="email" type="email" autoComplete="email" required maxLength={254}/></label>{mode!=="reset"&&<label>Password<div className="auth-password"><input name="password" type={visible?"text":"password"} autoComplete={mode==="register"?"new-password":"current-password"} required minLength={mode==="register"?12:1} maxLength={128}/><button type="button" aria-label={visible?"Hide password":"Show password"} aria-pressed={visible} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={20}/>:<Eye size={20}/>}</button></div>{mode==="register"&&<small>Use at least 12 characters.</small>}</label>}{mode==="login"&&<button type="button" className="auth-text" onClick={()=>change("reset")}>Forgot password?</button>}<button className="auth-primary" type="submit">{busy?"Please wait…":mode==="register"?"Create account":mode==="reset"?"Send reset link":"Sign in"}</button></fieldset></form><p className="auth-switch">{mode==="login"?"New to CreativistaPods? ":mode==="register"?"Already have an account? ":"Remember your password? "}<button type="button" disabled={busy} onClick={()=>change(mode==="login"?"register":"login")}>{mode==="login"?"Create an account":"Sign in"}</button></p></section><aside className="auth-story"><img src="/brand/reading-v2.png" alt="Children sharing a book in a colorful library"/><div><h2>Small groups.<br/><span>Big learning.</span></h2></div></aside></main><footer className="auth-footer"><span>© {new Date().getFullYear()} CreativistaPods</span><a href="mailto:admin@creativistapods.com">Need help? Contact our team</a></footer></div>;
}
