import { createClient } from "./supabase/server";
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
export async function identity(){const client=await createClient();const {data:{user},error}=await client.auth.getUser();if(error||!user||!user.email_confirmed_at)throw new HttpError(401,"Please sign in with a verified email address.");const active=await client.rpc("account_active");if(active.error)throw new Error(active.error.message);if(!active.data)throw new HttpError(403,"Your account is suspended. Contact our team for help.");const claimed=await client.rpc("claim_legacy_applications");if(claimed.error)throw new Error(claimed.error.message);const staff=await client.rpc("is_staff");if(staff.error)throw new Error(staff.error.message);const role=staff.data?await client.rpc("staff_roles"):{data:[],error:null};if(role.error)throw new Error(role.error.message);return {client,userId:user.id,email:user.email!,staff:!!staff.data,roles:(role.data||[]) as string[],role:((role.data||[]) as string[]).includes("Administrator")?"Administrator":role.data?.[0]||null};}
export async function owned(id:string,user:Awaited<ReturnType<typeof identity>>){const {data,error}=await user.client.from("applications").select("*").eq("id",id).maybeSingle();if(error)throw new Error(error.message);if(!data||(!user.staff&&data.owner!==user.userId))throw new HttpError(404,"Application not found.");return data;}
export function checkOrigin(request:Request){const origin=request.headers.get("origin");if(!origin||origin!==new URL(request.url).origin)throw new HttpError(403,"Refresh the page and try again.");}
export function fail(e:unknown){if(e instanceof HttpError)return Response.json({error:e.message},{status:e.status});console.error(e);return Response.json({error:"We couldn’t save or load your information. Please try again."},{status:503});}
export async function checked<T>(result:{data:T;error:{message:string}|null}){if(result.error)throw new Error(result.error.message);return result.data;}
export async function notify(email:string,subject:string,body:string){if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)return false;try{return (await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[email],subject,text:body})})).ok;}catch{return false;}}

export function permit(user:Awaited<ReturnType<typeof identity>>,section:string){if(!user.staff||!(user.roles.includes("Administrator")||user.roles.includes(section)))throw new HttpError(403,"Your role does not permit access to "+section+".");}
