import { z } from "zod";
import { applicationSchema, defaultSettings, statuses } from "../../../../lib/enrollment";
import { identity, permit, owned, checkOrigin, fail, HttpError, checked, notify } from "../../../../lib/server";
import {sendEmail,emailEnabled,paymentLinks} from "../../../../lib/email";
import {invoicePdf} from "../../../../lib/invoice-pdf";
export const dynamic="force-dynamic";
const headers={"Cache-Control":"private, no-store"};
export async function GET(request:Request){try{const user=await identity(),c=user.client,url=new URL(request.url),id=url.searchParams.get("id");if(url.searchParams.get("learning")==="1"){const applications=await checked(await c.from("applications").select("id").eq("owner",user.userId));const ids=(applications||[]).map(a=>a.id);const students=ids.length?await checked(await c.from("students").select("id,name,application_id").in("application_id",ids).order("name")):[];const studentIds=(students||[]).map(s=>s.id);const [progress,assignments]=await Promise.all([studentIds.length?c.from("student_progress").select("*").in("student_id",studentIds).order("recorded_on",{ascending:false}).order("id"):Promise.resolve({data:[],error:null}),studentIds.length?c.from("assignments").select("*").in("student_id",studentIds).order("created",{ascending:false}):Promise.resolve({data:[],error:null})]);return Response.json({students,progress:await checked(progress),assignments:await checked(assignments)},{headers});}if(url.searchParams.get("invoices")==="1"){let invoiceApps=c.from("applications").select("id");if(!user.staff)invoiceApps=invoiceApps.eq("owner",user.userId);const applications=await checked(await invoiceApps);const ids=(applications||[]).map(a=>a.id);const invoices=ids.length?await checked(await c.from("invoices").select("*").in("application_id",ids).order("due",{ascending:false})):[];return Response.json({invoices},{headers});}if(id){await owned(id,user);const [messages,documents,invoices]=await Promise.all([c.from("messages").select("*").eq("application_id",id).order("created"),c.from("documents").select("*").eq("application_id",id).order("created",{ascending:false}),c.from("invoices").select("*").eq("application_id",id)]);return Response.json({messages:await checked(messages),documents:await checked(documents),invoices:await checked(invoices)},{headers});}let query=c.from("applications").select("*").order("updated",{ascending:false});if(!user.staff||url.searchParams.get("staff")!=="1")query=query.eq("owner",user.userId);const [apps,settings]=await Promise.all([query,c.from("settings").select("data").eq("id","enrollment").maybeSingle()]);return Response.json({applications:await checked(apps),settings:(await checked(settings))?.data||defaultSettings,user:{email:user.email,staff:user.staff},emailEnabled:emailEnabled()},{headers});}catch(e){return fail(e);}}
export async function POST(request:Request){try{checkOrigin(request);const user=await identity(),c=user.client;const raw=await request.text();if(raw.length>60000)throw new HttpError(413,"This application is too large.");const b=JSON.parse(raw);if(user.staff){if(['invoice','invoiceEmail','invoicePaid'].includes(b.action))permit(user,'Invoices');else if(['settings','status','request','message'].includes(b.action))permit(user,'Applications');else if(['save','submit','update'].includes(b.action)&&b.id){const target=await owned(b.id,user);if(target.owner!==user.userId)permit(user,'Applications');}}const now=new Date().toISOString(),id=typeof b.id==="string"?b.id:crypto.randomUUID();
const message=async(body:string,kind="status",applicationId=id)=>checked(await c.from("messages").insert({id:crypto.randomUUID(),application_id:applicationId,author:user.staff?"CreativistaPods team":"Parent",body,kind,created:now}));
if(["save","submit","update"].includes(b.action)){
const existing=b.id?await owned(id,user):null;if(b.action==="update"&&!existing)throw new HttpError(400,"Choose an application to update.");if(b.action!=="update"&&existing&&existing.status!=="Draft")throw new HttpError(409,"Use Edit application to update a submitted application.");
const input={...b.data,funding:b.data.funding==="Discuss with staff"?"Family payment":b.data.funding};const draft=applicationSchema.innerType().partial().extend({parent:z.string().max(100),phone:z.string().max(30),email:z.string().max(254),homeAddress:z.string().max(500),children:z.array(z.object({name:z.string().max(100),age:z.union([z.literal(""),z.coerce.number().int().min(5).max(17)]),grade:z.string().max(60),goals:z.string().max(2000),supportAnswers:z.record(z.string().max(2000)).default({})})).min(1).max(10),consent:z.boolean()});const parsed=(b.action==="save"?draft:applicationSchema).safeParse(input);if(!parsed.success)throw new HttpError(400,parsed.error.issues[0].message);
const status=b.action==="update"?existing!.status:b.action==="submit"?"Submitted":"Draft";if(existing)await checked(await c.from("applications").update({data:parsed.data,status,updated:now}).eq("id",id));else await checked(await c.from("applications").insert({id,owner:user.userId,email:user.email,data:parsed.data,status,created:now,updated:now}));if(b.action!=="save")await message(b.action==="update"?"Application details updated.":"Application received. Our team will review your preferences and follow up here.");return Response.json({id,emailSent:false},{headers});}
if(b.action==="settings"){if(!user.staff)throw new HttpError(403,"Staff access is required.");const data=z.object({welcome:z.string().min(1).max(400),questions:z.array(z.string().trim().min(1).max(150)).max(8)}).parse(b.data);await checked(await c.from("settings").upsert({id:"enrollment",data}));return Response.json({ok:true},{headers});}
const a=await owned(id,user);
if(b.action==="message"||b.action==="request"){if(b.action==="request"&&!user.staff)throw new HttpError(403,"Staff access is required.");const body=z.string().trim().min(1).max(4000).parse(b.body);await message(body,b.action==="request"?"request":"message");if(b.action==="request")await checked(await c.from("applications").update({status:"Information requested",updated:now}).eq("id",id));const emailSent=user.staff?await notify(a.email,"An update on your CreativistaPods enrollment",body):false;return Response.json({ok:true,emailSent},{headers});}
if(!user.staff)throw new HttpError(403,"Staff access is required.");
if(b.action==="status"){const status=z.enum(statuses).parse(b.status);if(a.status==="Draft"||status==="Draft")throw new HttpError(409,"Parents must submit an application first.");await checked(await c.from("applications").update({status,updated:now}).eq("id",id));await message(`Enrollment status changed to ${status}.`);return Response.json({ok:true},{headers});}
if(b.action==="invoice"||b.action==="invoiceEmail"){
let invoice;
if(b.action==="invoice"){const i=z.object({description:z.string().trim().min(1).max(200),cents:z.number().int().min(1).max(10000000),due:z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Enter a due date with a four-digit year."),details:z.object({invoice_number:z.string().trim().max(60).optional().default(""),issue_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Enter an issue date with a four-digit year."),service_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Enter a service date with a four-digit year."),tutor:z.string().trim().max(100).optional().default(""),students:z.string().trim().min(1).max(500),terms:z.string().max(2000),items:z.array(z.object({description:z.string().trim().min(1).max(200),notes:z.string().max(1000),quantity:z.number().min(0.01).max(1000),unit_cents:z.number().int().min(1).max(10000000)})).min(1).max(20)}).optional(),url:z.union([z.literal(""),z.string().url().refine(v=>v.startsWith("https://"))]).optional().default("")}).parse(b.invoice);if(i.details){i.cents=i.details.items.reduce((sum,item)=>sum+Math.round(item.quantity*item.unit_cents),0);if(i.cents>10000000)throw new HttpError(400,"Invoice total exceeds $100,000.");}const links=paymentLinks();invoice={id:crypto.randomUUID(),application_id:id,...i,payment_method:a.data.funding==="Step Up for Students"?"Step Up for Students":"Family payment",url:i.url||(a.data.funding==="Step Up for Students"?links.stepUp:links.family),status:"Unpaid"};await checked(await c.from("invoices").insert(invoice));}
else{invoice=await checked(await c.from("invoices").select("*").eq("id",z.string().parse(b.invoiceId)).eq("application_id",id).single());if(!invoice)throw new HttpError(404,"Invoice not found.");}
const zelleDemo=(invoice.payment_method||a.data.funding)!=="Step Up for Students";
const body=["A new CreativistaPods invoice is available.",invoice.description,"Amount: $"+(invoice.cents/100).toFixed(2),"Due: "+invoice.due,zelleDemo?"":invoice.url?"Step Up link: "+invoice.url:"Please contact our team for payment instructions.",zelleDemo?"Attached: demonstration Zelle QR code only. It is NOT valid for payments. Contact our team for actual payment instructions.":"","View your invoice: https://creativistapods.com/portal"].join("\n");
const emailSent=await sendEmail(a.email,"Your CreativistaPods invoice",body,zelleDemo,await invoicePdf(invoice,a));await checked(await c.from("invoices").update({email_status:emailSent?"Sent":"Failed",email_sent_at:emailSent?new Date().toISOString():null}).eq("id",invoice.id));return Response.json({ok:true,emailSent,emailConfigured:emailEnabled(),message:emailSent?"Invoice saved and emailed.":emailEnabled()?"Invoice saved, but email sending failed. You can retry from invoice history.":"Invoice saved. Configure Hostinger email credentials in Vercel to send it."},{headers});}
if(b.action==="invoicePaid"){await checked(await c.from("invoices").update({status:"Paid"}).eq("id",z.string().parse(b.invoiceId)).eq("application_id",id));return Response.json({ok:true},{headers});}
throw new HttpError(400,"Unknown action.");
}catch(e){if(e instanceof z.ZodError)return Response.json({error:e.issues[0].message},{status:400});if(e instanceof SyntaxError)return Response.json({error:"Invalid request."},{status:400});return fail(e);}}
