import {z} from 'zod';
import {identity,permit,checkOrigin,checked,fail,HttpError} from '../../../../lib/server';
import {emailEnabled,paymentLinks,verifyEmail,sendEmail} from '../../../../lib/email';
export const dynamic='force-dynamic';
async function staff(){const u=await identity();if(!u.staff)throw new HttpError(403,'Staff access is required.');return u;}
export async function GET(){try{const u=await staff(),c=u.client;const can=(section:string)=>u.roles.includes('Administrator')||u.roles.includes(section);const empty=Promise.resolve({data:[],error:null});const [applications,students,progress,assignments,accounts,invoices,staffProfiles]=await Promise.all([c.from('applications').select('*').order('updated',{ascending:false}),can('Students')||can('Assignments')||can('Applications')?c.from('students').select('*').order('name'):empty,can('Students')?c.from('student_progress').select('*').order('recorded_on',{ascending:false}):empty,can('Assignments')?c.from('assignments').select('*').order('created',{ascending:false}):empty,can('Accounts')?c.rpc('admin_accounts'):Promise.resolve({data:{accounts:[],staff:[]},error:null}),can('Invoices')||can('Accounts')?c.from('invoices').select('*'):empty,can('Administrator')?c.rpc('staff_directory'):empty]);const dashboard=can('Dashboard')?await checked(await c.rpc('dashboard_totals')):null;return Response.json({dashboard,applications:await checked(applications),students:await checked(students),progress:await checked(progress),assignments:await checked(assignments),...await checked(accounts),invoices:await checked(invoices),paymentLinks:paymentLinks(),emailEnabled:emailEnabled(),roles:u.roles,role:u.role,staffProfiles:await checked(staffProfiles),currentUser:u.userId,currentEmail:u.email},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return fail(e);}}
export async function POST(req:Request){try{checkOrigin(req);const u=await staff(),c=u.client;const text=await req.text();if(text.length>16000)throw new HttpError(413,'Request too large.');const b=JSON.parse(text);const section=b.action==='staffProfile'||b.action==='staffStatus'||b.action==='deleteStaff'||b.action==='deleteFamily'||(b.action==='account'&&b.kind==='staff')||b.action==='verifyEmail'?'Administrator':b.action==='account'||b.action==='contact'?'Accounts':b.action==='assignment'||b.action==='assignmentStatus'?'Assignments':['student','studentDays','studentPod','progress','progressEmail'].includes(b.action)?'Students':'Administrator';permit(u,section);
if(b.action==='staffInvite'){const d=z.object({email:z.string().email()}).parse(b.data);const directory=await checked(await c.rpc('staff_directory'));const recipient=directory.find((person:{email:string;name?:string;roles:string[]})=>person.email.toLowerCase()===d.email.toLowerCase());if(!recipient||!recipient.roles?.length)throw new HttpError(400,'Save staff access before sending an invitation.');const ok=await sendEmail(recipient.email,'Your CreativistaPods staff invitation',`Hello ${recipient.name||'there'},\n\nYou have been invited to the CreativistaPods staff workspace.\n\nSign in or create your account using this email address at:\nhttps://creativistapods.com/portal/login\n\nOnce signed in, open the staff workspace:\nhttps://creativistapods.com/portal/admin\n\nCreativistaPods`);if(!ok)throw new HttpError(503,'Invitation email could not be sent. Please try again.');return Response.json({ok:true,message:'Staff invitation email sent.'});}if(b.action==='staffProfile'){const d=z.object({email:z.string().email(),originalEmail:z.string().email().optional(),name:z.string().trim().min(1).max(100),roles:z.array(z.enum(['Administrator','Dashboard','Accounts','Applications','Assignments','Invoices','Students'])).max(7)}).parse(b.data);await checked(await c.rpc('edit_staff_profile',{original_email:d.originalEmail||d.email,target:d.email,display_name:d.name,permissions:d.roles}));return Response.json({ok:true});}
if(b.action==='verifyEmail'){const ok=await verifyEmail();return Response.json({ok,message:ok?'Hostinger email connection verified.':'Hostinger connection failed. Check the mailbox credentials in Vercel.'});}
if(b.action==='staffStatus'){const d=z.object({userId:z.string().uuid(),status:z.enum(['Active','Suspended'])}).parse(b.data);await checked(await c.rpc('manage_account',{action:'suspend',target:d.userId,enabled:d.status==='Suspended'}));return Response.json({ok:true,message:`Staff account ${d.status.toLowerCase()}.`});}
if(b.action==='deleteStaff'){const d=z.object({email:z.string().email()}).parse(b.data);await checked(await c.rpc('delete_staff_member',{target_email:d.email}));return Response.json({ok:true,message:'Staff access deleted.'});}
if(b.action==='deleteFamily'){const d=z.object({userId:z.string().uuid()}).parse(b.data);if(d.userId===u.userId)throw new HttpError(400,'You cannot delete your own account.');const directory=await checked(await c.rpc('staff_directory'));if((directory||[]).some((person:{user_id?:string})=>person.user_id===d.userId))throw new HttpError(400,'Delete staff access from Staff Admin first.');const applications=await checked(await c.from('applications').select('id').eq('owner',d.userId));const applicationIds=(applications||[]).map((application:{id:string})=>application.id);if(applicationIds.length){const documents=await checked(await c.from('documents').select('id,application_id').in('application_id',applicationIds));const paths=(documents||[]).map((document:{id:string;application_id:string})=>`${document.application_id}/${document.id}`);if(paths.length)await checked(await c.storage.from('enrollment-documents').remove(paths));}await checked(await c.rpc('delete_family_account',{target_user:d.userId}));return Response.json({ok:true,message:'Family account deleted.'});}
if(b.action==='student'){const d=z.object({application_id:z.string().min(1),name:z.string().trim().min(1).max(100),grade:z.string().max(60)}).parse(b.data);await checked(await c.from('students').insert(d));}
else if(b.action==='studentDays'){const d=z.object({student_id:z.string().uuid(),days:z.array(z.enum(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'])).max(7)}).parse(b.data);const updated=await checked(await c.from('students').update({days:[...new Set(d.days)]}).eq('id',d.student_id).select('id').maybeSingle());if(!updated)throw new HttpError(404,'Student not found.');}
else if(b.action==='studentPod'){const d=z.object({student_id:z.string().uuid(),pod:z.string().trim().max(100)}).parse(b.data);const updated=await checked(await c.from('students').update({pod:d.pod}).eq('id',d.student_id).select('id').maybeSingle());if(!updated)throw new HttpError(404,'Student not found.');}
else if(b.action==='progress'||b.action==='progressEmail'){const d=z.object({student_id:z.string().uuid(),subject:z.string().trim().max(100).default(''),rating:z.enum(['Needs support','Developing','On track','Exceeding']),notes:z.string().trim().min(1).max(4000),recorded_on:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}).parse(b.data);if(b.action==='progressEmail'){const student=await checked(await c.from('students').select('name,application_id').eq('id',d.student_id).single());if(!student)throw new HttpError(404,'Student not found.');const application=await checked(await c.from('applications').select('email,data').eq('id',student.application_id).single());const recipient=z.string().email().parse(application?.email);const ok=await sendEmail(recipient,'Progress update for '+student.name,`Hello ${application?.data?.parent||'family'},\n\nProgress update for ${student.name}\nSubject: ${d.subject}\nDate: ${d.recorded_on}\nProgress: ${d.rating}\n\n${d.notes}\n\nCreativistaPods`);if(!ok)throw new HttpError(503,'Email could not be sent. Please try again.');const existing=await checked(await c.from('student_progress').select('id').eq('student_id',d.student_id).eq('subject',d.subject).eq('rating',d.rating).eq('notes',d.notes).eq('recorded_on',d.recorded_on).limit(1));if(!existing?.length)await checked(await c.from('student_progress').insert(d));return Response.json({ok:true,message:'Email sent to the family.'});}await checked(await c.from('student_progress').insert(d));}
else if(b.action==='assignment'){const d=z.object({student_id:z.string().uuid(),title:z.string().trim().min(1).max(200),instructions:z.string().max(4000),due:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(),document_id:z.string().nullable()}).parse(b.data);if(d.document_id){const s=await checked(await c.from('students').select('application_id').eq('id',d.student_id).single());const doc=await checked(await c.from('documents').select('application_id').eq('id',d.document_id).single());if(!s||!doc||s.application_id!==doc.application_id)throw new HttpError(400,'Attachment must belong to this student’s family.');}await checked(await c.from('assignments').insert(d));}
else if(b.action==='assignmentStatus'){const status=z.enum(['Assigned','In progress','Completed']).parse(b.status);await checked(await c.from('assignments').update({status}).eq('id',z.string().uuid().parse(b.id)));}
else if(b.action==='account'){const action=z.enum(['suspend','staff']).parse(b.kind),target=(action==='staff'?z.string().email():z.string().uuid()).parse(b.target),enabled=z.boolean().parse(b.enabled);await checked(await c.rpc('manage_account',{action,target,enabled}));}
else if(b.action==='contact'){const id=z.string().parse(b.id),contact=z.object({parent:z.string().trim().min(2).max(100),phone:z.string().min(7).max(30),homeAddress:z.string().min(5).max(500)}).parse(b.data);const a=await checked(await c.from('applications').select('data').eq('id',id).single());await checked(await c.from('applications').update({data:{...a!.data,...contact},updated:new Date().toISOString()}).eq('id',id));}
else throw new HttpError(400,'Unknown action.');return Response.json({ok:true});}catch(e){if(e instanceof z.ZodError)return Response.json({error:e.issues[0].message},{status:400});return fail(e);}}
